package infrastructure_technique

import domain_technique "jiu-tracker/src/modules/technique/domain"

// TechniqueFixtures returns technique seed data (idempotent by ID).
func TechniqueFixtures() []domain_technique.Technique {
	return []domain_technique.Technique{
		{
			ID:                    "sub-beg-001",
			Name:                  "Rear Naked Choke",
			NamePortuguese:        "Mata Leão",
			Description:           "A blood choke applied from the back.",
			DescriptionPortuguese: "Um estrangulamento sanguíneo aplicado pelas costas.",
			Category:              domain_technique.Submission,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "sub-beg-002",
			Name:                  "Cross Collar Choke",
			NamePortuguese:        "Estrangulamento de Gola Cruzada",
			Description:           "A gi choke from mount or closed guard.",
			DescriptionPortuguese: "Um estrangulamento de gi realizado da montada ou guarda fechada.",
			Category:              domain_technique.Submission,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "sub-beg-003",
			Name:                  "Straight Armbar from Guard",
			NamePortuguese:        "Chave de Braço da Guarda",
			Description:           "A joint lock applied from closed guard.",
			DescriptionPortuguese: "Uma chave articular aplicada da guarda fechada.",
			Category:              domain_technique.Submission,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "sub-int-001",
			Name:                  "Triangle Choke",
			NamePortuguese:        "Triângulo",
			Description:           "A choke applied from guard with the legs.",
			DescriptionPortuguese: "Um estrangulamento aplicado da guarda com as pernas.",
			Category:              domain_technique.Submission,
			Difficulty:            domain_technique.Intermediate,
		},
		{
			ID:                    "sub-int-002",
			Name:                  "Kimura",
			NamePortuguese:        "Kimura",
			Description:           "A double-joint shoulder lock.",
			DescriptionPortuguese: "Uma chave dupla de ombro.",
			Category:              domain_technique.Submission,
			Difficulty:            domain_technique.Intermediate,
		},
		{
			ID:                    "swp-beg-001",
			Name:                  "Scissor Sweep",
			NamePortuguese:        "Raspagem Tesoura",
			Description:           "A fundamental sweep from closed guard.",
			DescriptionPortuguese: "Uma raspagem fundamental da guarda fechada.",
			Category:              domain_technique.Sweep,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "swp-beg-002",
			Name:                  "Hip Bump Sweep",
			NamePortuguese:        "Raspagem de Quadril",
			Description:           "A sweep from closed guard using the hips.",
			DescriptionPortuguese: "Uma raspagem da guarda fechada usando os quadris.",
			Category:              domain_technique.Sweep,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "pas-beg-001",
			Name:                  "Double Under Pass",
			NamePortuguese:        "Passagem por Baixo Dupla",
			Description:           "A guard pass with both underhooks.",
			DescriptionPortuguese: "Uma passagem de guarda com ambos os underhooks.",
			Category:              domain_technique.Pass,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "pas-beg-002",
			Name:                  "Knee Slice Pass",
			NamePortuguese:        "Passagem com Joelho",
			Description:           "A fundamental guard pass with the knee.",
			DescriptionPortuguese: "Uma passagem de guarda fundamental com o joelho.",
			Category:              domain_technique.Pass,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "grd-beg-001",
			Name:                  "Closed Guard",
			NamePortuguese:        "Guarda Fechada",
			Description:           "The most fundamental guard position.",
			DescriptionPortuguese: "A posição de guarda mais fundamental.",
			Category:              domain_technique.Guard,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "grd-beg-002",
			Name:                  "Half Guard",
			NamePortuguese:        "Meia Guarda",
			Description:           "A guard controlling one of the opponent's legs.",
			DescriptionPortuguese: "Uma guarda controlando uma das pernas do oponente.",
			Category:              domain_technique.Guard,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "tkd-beg-001",
			Name:                  "Double Leg Takedown",
			NamePortuguese:        "Queda Dupla",
			Description:           "A fundamental wrestling takedown.",
			DescriptionPortuguese: "Uma queda fundamental de luta.",
			Category:              domain_technique.Takedown,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "def-beg-001",
			Name:                  "Elbow-Knee Escape (Shrimping)",
			NamePortuguese:        "Fuga Camarão",
			Description:           "The fundamental escape from bottom positions.",
			DescriptionPortuguese: "A fuga mais fundamental de posições por baixo.",
			Category:              domain_technique.Defend,
			Difficulty:            domain_technique.Beginner,
		},
		{
			ID:                    "esc-beg-001",
			Name:                  "Armbar Defense (Stacking)",
			NamePortuguese:        "Defesa de Chave de Braço (Empilhamento)",
			Description:           "A defense against the armbar by stacking.",
			DescriptionPortuguese: "Uma defesa contra a chave de braço por empilhamento.",
			Category:              domain_technique.SubmissionEscape,
			Difficulty:            domain_technique.Beginner,
		},
	}
}
